import "@radix-ui/themes/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import Navbar from "./_navbarsComponents/Navbar";
import { Container, Theme } from "@radix-ui/themes";
import { Inter } from "next/font/google";
import QueryClientProvider from "./QueryClientProvider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <QueryClientProvider>
          <SessionProvider>
            <Theme accentColor="jade" grayColor="mauve" radius="large">
              {/* <Nav /> */}
              <Navbar />
              <main className="p-5">
                {" "}
                <Container>{children}</Container>
              </main>
            </Theme>
          </SessionProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
